name: Build, Test and Deploy to Github Pages

on:
  push:
    branches:
      - master

jobs:
  cicd:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: setup node 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    
    - name: install
      run: npm ci

    - name: tests
      if: success()
      run: npm run eslint && npm test

    - name: build
      if: success()
      run: npm run build

    - name: deploy
      if: success()
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.ACCESS_TOKEN }}
        publish_dir: ./public
